# Generated by Django 5.2.1 on 2025-06-06 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoverageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.applicationtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='carriers',
            field=models.ManyToManyField(to='core.carrier'),
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='coverages',
            field=models.ManyToManyField(to='core.coverageline'),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='insurance_types',
            field=models.ManyToManyField(to='core.insurancetype'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='insurance_types',
            field=models.ManyToManyField(to='core.insurancetype'),
        ),
        migrations.AddField(
            model_name='applicationtemplate',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.insurancetype'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('carriers', models.ManyToManyField(blank=True, to='core.carrier')),
                ('coverages', models.ManyToManyField(blank=True, to='core.coverageline')),
                ('insurance_types', models.ManyToManyField(to='core.insurancetype')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.applicationsession')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateQuestionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('original_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_snapshots', to='core.applicationtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.applicationsession')),
                ('question_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.templatequestionsnapshot')),
            ],
        ),
    ]
