# Generated by Django 5.2.1 on 2025-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='carriers',
            field=models.ManyToManyField(blank=True, to='core.carrier'),
        ),
        migrations.AlterField(
            model_name='question',
            name='coverages',
            field=models.ManyToManyField(blank=True, to='core.coverageline'),
        ),
    ]
