# Generated by Django 5.2.3 on 2025-07-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_applicationtemplate_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsession',
            name='insured_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
