# Generated by Django 5.2.1 on 2025-05-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_carriers_alter_question_coverages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsession',
            name='carriers',
            field=models.ManyToManyField(blank=True, to='core.carrier'),
        ),
        migrations.AlterField(
            model_name='applicationsession',
            name='coverages',
            field=models.ManyToManyField(blank=True, to='core.coverageline'),
        ),
    ]
